loginAPLICATIONS/account/urls.py
from django.urls import path
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView, LogoutView
from .forms import CustomUserCreationForm
from .views import *
app_name = 'account'

urlpatterns = [
   path('', LoginView.as_view(
        template_name='login.html'
    ), name='login'),
   
    path('signup/', CreateView.as_view(
        template_name='signup.html',
        form_class=CustomUserCreationForm,
        success_url='/account/login',
    ), name='signup'),
    path('login/', LoginView.as_view(
        redirect_authenticated_user=True,
        template_name='login.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', UserDetail.as_view(), name='profile'),
		path('user_update/<int:pk>/', UserUpdate.as_view(), name='user_update'),
		path('password_change/', PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDone.as_view(), name='password_change_done'),
		path('user_delete/<int:pk>/', UserDelete.as_view(), name='user_delete'),
]

loginAPLICATIONS/loginTask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('tasks/', include('tasks.urls')),
    path('', include('account.urls')),   
]

loginAPLICATIONS/tasks/urls.py
from django.urls import path
from . import views
app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('detail/<int:task_id>', views.detail, name='detail'),
    path('edit/<int:task_id>', views.edit, name='edit'),
    path('delete/<int:task_id>', views.delete, name='delete'),
]

loginAPLICATIONS/account/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(_('username'), max_length=150)
    email = models.EmailField(_('email address'), unique=True)
    age = models.PositiveIntegerField(_('age'), default=0, blank=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(_('active'), default=True)
    data_joined = models.DateTimeField(_('data joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = 'users'
        swappable = 'AUTH_USER_MODEL'

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

loginAPLICATIONS/tasks/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return f'{self.title}, {self.content}'

loginAPLICATIONS/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('email', 'age')


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            'username',
            'email',
            'age',
        )

loginAPLICATIONS/tasks/forms.py
from django import forms


class TaskCreationForm(forms.Form):
    title = forms.CharField(label='Title', max_length=255)
    content = forms.CharField(label='Content', widget=forms.Textarea())

loginAPLICATIONS/account/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.views.generic import DetailView, UpdateView, DeleteView
from .forms import UserUpdateForm

User = get_user_model()

class UserDetail(DetailView):
    model = User
    template_name = 'profile.html'

class UserUpdate(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'user_edit.html'

    def get_success_url(self):
        return reverse('account:profile', kwargs={'pk': self.kwargs['pk']})

class PasswordChange(PasswordChangeView):
    template_name = 'password_change.html'
    success_url = reverse_lazy('account:password_change_done')

class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'profile.html'

class UserDelete(DeleteView):
    model = User
    template_name = 'user_delete.html'
    success_url = reverse_lazy('account:login')

loginAPLICATIONS/tasks/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Task
from .forms import TaskCreationForm


def index(request):
    tasks = Task.objects.all()
    params = {
        'tasks': tasks,
    }
    return render(request, 'tasks/index.html', params)


def create(request):
    if (request.method == 'POST'):
        title = request.POST['title']
        content = request.POST['content']
        task = Task(title=title, content=content)
        task.save()
        return redirect('tasks:index')
    else:
        params = {
            'form': TaskCreationForm(),
        }
        return render(request, 'tasks/create.html', params)


def detail(request, task_id):
    task = Task.objects.get(id=task_id)
    params = {
        'task': task,
    }
    return render(request, 'tasks/detail.html', params)


def edit(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.title = request.POST['title']
        task.content = request.POST['content']
        task.save()
        return redirect('tasks:detail', task_id)
    else:
        form = TaskCreationForm(initial={
            'title': task.title,
            'content': task.content,
        })
        params = {
            'task': task,
            'form': form,
        }
        return render(request, 'tasks/edit.html', params)


def delete(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.delete()
        return redirect('tasks:index')
    else:
        params = {
            'task': task,
        }
        return render(request, 'tasks/delete.html', params)

loginAPLICATIONS/account/templates/login.html
{% extends "base.html" %}

{% block main %}
<h2>Login Page</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Login">
</form>
{% endblock %}

loginAPLICATIONS/account/templates/password_change.html
{% extends "base.html" %}

{% block main %}
<h2>Password Change Page</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Change">
</form>
<a href="{% url 'account:profile' user.id %}">Back</a>
{% endblock %}

loginAPLICATIONS/account/templates/profile.html
{% extends "base.html" %}

{% block main %}
<h2>User Detail Page</h2>
<section>
  <ul>
    <li>Username: {{ user.username }}</li>
    <li>Mail addres: {{ user.email }}</li>
    <li>Age: {{ user.age }}</li>
  </ul>
  <a href="{% url 'account:user_update' user.id %}">Edit</a>
  <a href="{% url 'account:password_change' %}">Change password</a>
</section>
{% endblock %}

loginAPLICATIONS/account/templates/signup.html
{% extends "base.html" %}

{% block main %}
<h2>Signup Page</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Register">
</form>
{% endblock %}

loginAPLICATIONS/account/templates/user_delete.html
{% extends "base.html" %}

{% block main %}
<h2>User Delete Page</h2>
<section>
  <form method="delete">
    <ul>
      <li>Username: {{ user.username }}</li>
      <li>Mail addres: {{ user.email }}</li>
      <li>Age: {{ user.age }}</li>
    </ul>
    <input type="submit" value="Delete">
  </form>
  <a href="{% url 'account:profile' user.id %}">Return</a>
</section>
{% endblock %}

loginAPLICATIONS/account/templates/user_edit.html
{% extends "base.html" %}

{% block main %}
<h2>User Edit Page</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>
<a href="{% url 'account:profile' user.id %}">Back</a>
<a href="{% url 'account:user_delete' user.id  %}">Delete</a>
{% endblock %}

loginAPLICATIONS/tasks/templates/tasks/create.html
{% extends "base.html" %}

{% block main %}
<h1>Create Task</h1>
<form action="{% url 'tasks:create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create">
</form>

<br>

<a href="{% url 'tasks:index' %}">Create</a>
{% endblock %}

loginAPLICATIONS/tasks/templates/tasks/delete.html
{% extends "base.html" %}

{% block main %}
<h1>Delete Task</h1>
<p>
  <strong>Title:</strong>
  {{task.title}}
</p>

<p>
  <strong>Content:</strong>
  {{task.content}}
</p>
<form action="{% url 'tasks:delete' task.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Delete">
</form>

<br>

<a href="{% url 'tasks:index' %}">Back</a>
{% endblock %}

loginAPLICATIONS/tasks/templates/tasks/detail.html
{% extends "base.html" %}

{% block main %}
<h1>Task</h1>
<p>
  <strong>Title:</strong>
  {{task.title}}
</p>

<p>
  <strong>Content:</strong>
  {{task.content}}
</p>
<a href="{% url 'tasks:index' %}">Back</a> |
<a href="{% url 'tasks:edit' task.id %}">Edit</a>
{% endblock %}

loginAPLICATIONS/tasks/templates/tasks/edit.html
{% extends "base.html" %}

{% block main %}
<h1>Edit Task</h1>
<form action="{% url 'tasks:edit' task.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Edit">
</form>

<br>

<a href="{% url 'tasks:detail' task.id %}">Detail</a> |
<a href="{% url 'tasks:index' %}">Back</a>

{% endblock %}

loginAPLICATIONS/tasks/templates/tasks/index.html
{% extends "base.html" %}

{% block main %}
<h1>Task list page</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  {% for task in tasks %}
  <tr>
    <td>{{task.title}}</td>
    <td>{{task.content}}</td>
    <td><a href="{% url 'tasks:detail' task.id %}">Detail</a></td>
    <td><a href="{% url 'tasks:edit' task.id %}">Edit</a></td>
    <td><a href="{% url 'tasks:delete' task.id %}">Delete</a></td>
  </tr>
  {% endfor %}
</table>

<br>

<a href="{% url 'tasks:create' %}">Create</a>

{% endblock %}

loginAPLICATIONS/templates/base.html
{% load static %}

<html>

<head>
  <meta charset="utf-8">
  <title>Task</title>
  <link rel="stylesheet" href="{% static 'tasks/css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'tasks/css/style.css' %}">
</head>

<body>
  <nav>
    <ul>
      {% if user.is_authenticated %}
      <li><a href="{% url 'account:profile' user.id %}">Account details</a></li>
      <li><a href="{% url 'account:logout' %}">Logout</a></li>
      <li><a href="{% url 'tasks:index' %}">Task list</a></li>
      {% else %}
      <li><a href="{% url 'account:login' %}">Login</a></li>
      <li><a href="{% url 'account:signup' %}">Sign Up</a></li>
      {% endif %}
    </ul>
  </nav>
  <main>
    <div>
      {% block main %}
      {% endblock %}
    </div>
  </main>
</body>

</html>